server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  datasource:
    # url: jdbc:postgresql://localhost:5432/database
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://primary.database--ls828smnbk6x.addon.code.run:5432/database}
    username: ${USERNAME:postgres}
    password: ${PASSWORD:password}
    driver-class-name: org.postgresql.Driver  # Explicit driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  datasource.hikari:
    connection-timeout: 30000  # Extend timeout for HikariCP

logging:
  level:
    org.springframework.security: DEBUG