server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  datasource:
    # url: jdbc:postgresql://localhost:5432/database or //db since docker
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver  # Explicit driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  datasource.hikari:
    connection-timeout: 30000  # Extend timeout for HikariCP

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.security: DEBUG